### ISSUE TITLE
Swarm role assumes Ubuntu Xenial 16.04 when installing docker

### ISSUE THREAD

**Issue by ieugen** [JoelLefkowitz/swarmroles#6]
Hi, 

When installing docker this assumes Ubuntu Xenial. 
I think this should be more generic or at least not hardcoded.

For example I am installing on Ubuntu 20.04 . 
```

TASK [joellefkowitz.swarmroles.docker : Register Docker Repository] ********************************************************************************************************************************
ansible/collections/ansible_collections/joellefkowitz/swarmroles/roles/docker/tasks/main.yml:6
ok: [stage1] => {"changed": false, "repo": "deb https://download.docker.com/linux/ubuntu xenial stable", "state": "present"}
```

**Comment by ieugen** [comment]
Another option would be to allow skipping docker installation and allow user to install docker on it's own, in a separate task.

**Comment by JoelLefkowitz** [comment]
Im going to look into now

**Comment by ieugen** [comment]
This is how we setup docker right now which is not very different then how you do it.

I think the option to opt in for docker install is the best one.
It's one line in the playbook to add the docker role + variables. 

Also having the option to OPT-IN for docker install (instead of depending on it automatically) will probably make the playbook faster since it will avoid running the docker tasks over and over again like it does now we use the example in the readme. 

```
---
# tasks file for docker

- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python3-pip
    - python3-setuptools

- name: Add Docker GPG apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker apt repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
    update_cache: yes

- name: Install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: yes

- name: Set Docker daemon configuration
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "mtu": 9000,
        "insecure-registries" : ["registry:5000"]
      }

- name: Reload Docker daemon configuration
  service:
    name: docker
    state: reloaded

- name: Ensure Docker daemon is started and enabled at boot
  service:
    name: docker
    state: started
    enabled: true
    
- name: 'Ensure the user {{ ansible_user }} is in the docker group'
  user: 
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Install Docker modules for Python
  pip:
    name:
      - docker
      - jsondiff==1.2.0
      - pyyaml==5.4.1

- name: Install docker-compose
  get_url:
    url : https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: "+x"
```
